version: "3.8"
services:
  judge0:
    image: judge0/api:1.13.0
    ports:
      - "2358:2358"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=default
      - DB_PASSWORD=password
      - DB_NAME=judge0
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=judge0
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:6
